### ISSUE TITLE
Temporal/Geographical Map

### ISSUE THREAD

**Issue by bowmanj17** [WL-Biol185-ShinyProjects/CWP-trends#2]
County map of the US, with each ~10 year time frame in its own map colored by intensity of either PMF or CWP cases (drop bar box). Potentially have data/stats pop up when county/region clicked?

**Comment by northm17** [comment]
We have decided to consolidate this to one plot and use a play button to activate movement through the entire time period. The play button will allow us to watch geographic changes happen in an animated form.
Add the ability to click on a county to pull up statistics on the region the county belongs to. The details should include avg. exposure, avg. tenure, coal rank, and avg. miner age.

**Comment by bowmanj17** [comment]
The plot is now implemented. Need to edit the colors and add in popup statistics for each region.
