### ISSUE TITLE
Exposure and Tenure Bar Plots

### ISSUE THREAD

**Issue by bowmanj17** [WL-Biol185-ShinyProjects/CWP-trends#3]
2 Bar plots (exposure and tenure lengths) with age as x-axis. Plot number of cat1, number of cat2, and number PMF for each age category. Filtered by slider input of either exposure or tenure length. Bars for each sub variable (box plots) should be colored by coal rank (use ncsr4, DO NOT USE ncsr1).

**Comment by northm17** [comment]
combine into one. make a drop down box to select exposure or tenure which then pops up the slider for what you selected.

**Comment by northm17** [comment]
back to two different plots because tenure and exposure are on two different mismatching datasets.
